name: CI Basique

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
      - name: ğŸ“¥ Get code
        uses: actions/checkout@v4
      
      - name: ğŸ“ List files
        run: ls -la
      
      - name: ğŸ³ Build Docker
        run: |
          docker build -t app-ci .
          docker images
